In [71]:
import pathlib
import pandera.polars as pa
import pandera.typing.polars
from pandera.typing.polars import DataFrame
from pandera.typing.polars import Series
import polars as pl
from typing import Annotated
import matplotlib.pyplot as plt

In [72]:
## CONSTANTS
CCYS = ['jpy','chf','cad','aud','nzd','eur','gbp']
INVERSE_CCYS = ['chf','jpy','cad']

In [73]:
def get_file_path(ccy: str):
    if ccy in INVERSE_CCYS:
        pair = f'usd{ccy}'
    else:
        pair = f'{ccy}usd'
    return pathlib.Path(r'D:\Trading\2026\\',f"{pair}_d1.csv")

In [74]:
class DayBar(pa.DataFrameModel):
    timestamp: pandera.typing.polars.Series[pl.Datetime("ns", "UTC")]
    open: pandera.typing.polars.Series[float]
    high: pandera.typing.polars.Series[float]
    low: pandera.typing.polars.Series[float]
    close: pandera.typing.polars.Series[float]

In [75]:
def read_data(ccy: str) -> DataFrame[DayBar]:
    df = pl.read_csv(get_file_path(ccy))

    df = df.with_columns(
        pl.from_epoch("timestamp", time_unit="ms")
          .dt.cast_time_unit("ns")
          .dt.replace_time_zone("UTC")
    )

    if ccy in INVERSE_CCYS:
        df = df.with_columns(
            (1 / pl.col("open")).alias(f"open"),
            (1 / pl.col("high")).alias("high"),
            (1 / pl.col("low")).alias("low"),
            (1 / pl.col("close")).alias("close"),
        )
    return DayBar.validate(df)

In [76]:
bar_dict = {x: read_data(x) for x in CCYS}

In [77]:
renamed_dict = {
    ccy: bar_dict[ccy].select("timestamp",
                              pl.col("open").alias(f"{ccy}_open"),
                              pl.col("high").alias(f"{ccy}_high"),
                              pl.col("low").alias(f"{ccy}_low"),
                              pl.col("close").alias(f"{ccy}_close"))
    for ccy in CCYS
}

In [90]:
def add_return(df: pl.DataFrame, lookback: int) -> pl.DataFrame:
    df = df.with_columns(
        [(pl.col(f"{ccy}_close")/pl.col(f"{ccy}_close").shift(lookback)-1).alias(f"{ccy}_return_{lookback}") for ccy in CCYS])
    return df
git

In [ ]:
def calculate_target(df: pl.DataFrame, ccy: str) -> pl.DataFrame:
    #calculate the cross sectional 1 day return (handle multiple day look forward?
    ccy_returns = []
    relative_return =
    return relative_return

In [91]:
# Align each close series by its timestamp; retain timestamps present in any pair.
all = (
    pl.concat(renamed_dict.values(), how="align_full")
    .sort("timestamp")
).drop_nulls()
all

shape: (6_502, 29)
┌──────────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬─────────┬───────────┐
│ timestamp    ┆ jpy_open ┆ jpy_high ┆ jpy_low  ┆ … ┆ gbp_open ┆ gbp_high ┆ gbp_low ┆ gbp_close │
│ ---          ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---     ┆ ---       │
│ datetime[ns, ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64     ┆ f64       │
│ UTC]         ┆          ┆          ┆          ┆   ┆          ┆          ┆         ┆           │
╞══════════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪═════════╪═══════════╡
│ 2000-03-03   ┆ 0.00927  ┆ 0.009256 ┆ 0.009316 ┆ … ┆ 1.5769   ┆ 1.584    ┆ 1.5754  ┆ 1.5778    │
│ 00:00:00 UTC ┆          ┆          ┆          ┆   ┆          ┆          ┆         ┆           │
│ 2000-03-04   ┆ 0.009283 ┆ 0.009283 ┆ 0.009283 ┆ … ┆ 1.5778   ┆ 1.5778   ┆ 1.5778  ┆ 1.5778    │
│ 00:00:00 UTC ┆          ┆          ┆          ┆   ┆          ┆          ┆         ┆           │
│ 2000-03-05   ┆ 0.009283 ┆ 0.009283 ┆ 0.009283 ┆ … ┆ 1.5778   ┆ 1.5778   ┆ 1.5778  ┆ 1.5778    │
│ 00:00:00 UTC ┆          ┆          ┆          ┆   ┆          ┆          ┆         ┆           │
│ 2000-03-06   ┆ 0.009271 ┆ 0.009266 ┆ 0.009368 ┆ … ┆ 1.5772   ┆ 1.5823   ┆ 1.5713  ┆ 1.5748    │
│ 00:00:00 UTC ┆          ┆          ┆          ┆   ┆          ┆          ┆         ┆           │
│ 2000-03-07   ┆ 0.0093   ┆ 0.009248 ┆ 0.009451 ┆ … ┆ 1.5745   ┆ 1.5821   ┆ 1.5695  ┆ 1.5796    │
│ 00:00:00 UTC ┆          ┆          ┆          ┆   ┆          ┆          ┆         ┆           │
│ …            ┆ …        ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …       ┆ …         │
│ 2024-12-27   ┆ 0.006339 ┆ 0.006331 ┆ 0.006355 ┆ … ┆ 1.25273  ┆ 1.25922  ┆ 1.25046 ┆ 1.25714   │
│ 00:00:00 UTC ┆          ┆          ┆          ┆   ┆          ┆          ┆         ┆           │
│ 2024-12-28   ┆ 0.006339 ┆ 0.006339 ┆ 0.006339 ┆ … ┆ 1.25714  ┆ 1.25714  ┆ 1.25714 ┆ 1.25714   │
│ 00:00:00 UTC ┆          ┆          ┆          ┆   ┆          ┆          ┆         ┆           │
│ 2024-12-29   ┆ 0.006342 ┆ 0.006333 ┆ 0.006343 ┆ … ┆ 1.25706  ┆ 1.25876  ┆ 1.25615 ┆ 1.25775   │
│ 00:00:00 UTC ┆          ┆          ┆          ┆   ┆          ┆          ┆         ┆           │
│ 2024-12-30   ┆ 0.006333 ┆ 0.006326 ┆ 0.006383 ┆ … ┆ 1.25775  ┆ 1.26071  ┆ 1.25057 ┆ 1.25429   │
│ 00:00:00 UTC ┆          ┆          ┆          ┆   ┆          ┆          ┆         ┆           │
│ 2024-12-31   ┆ 0.006369 ┆ 0.006347 ┆ 0.006409 ┆ … ┆ 1.25478  ┆ 1.2569   ┆ 1.25052 ┆ 1.25116   │
│ 00:00:00 UTC ┆          ┆          ┆          ┆   ┆          ┆          ┆         ┆           │
└──────────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴─────────┴───────────┘

In [92]:
all = add_return(all, 1)

In [93]:
all

shape: (6_502, 36)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ timestamp  ┆ jpy_open ┆ jpy_high ┆ jpy_low  ┆ … ┆ aud_return ┆ nzd_retur ┆ eur_retur ┆ gbp_retur │
│ ---        ┆ ---      ┆ ---      ┆ ---      ┆   ┆ _1         ┆ n_1       ┆ n_1       ┆ n_1       │
│ datetime[n ┆ f64      ┆ f64      ┆ f64      ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│ s, UTC]    ┆          ┆          ┆          ┆   ┆ f64        ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2000-03-03 ┆ 0.00927  ┆ 0.009256 ┆ 0.009316 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 00:00:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ UTC        ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2000-03-04 ┆ 0.009283 ┆ 0.009283 ┆ 0.009283 ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 00:00:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ UTC        ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2000-03-05 ┆ 0.009283 ┆ 0.009283 ┆ 0.009283 ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 00:00:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ UTC        ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2000-03-06 ┆ 0.009271 ┆ 0.009266 ┆ 0.009368 ┆ … ┆ -0.010357  ┆ -0.013088 ┆ 0.001357  ┆ -0.001901 │
│ 00:00:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ UTC        ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2000-03-07 ┆ 0.0093   ┆ 0.009248 ┆ 0.009451 ┆ … ┆ 0.004485   ┆ 0.002901  ┆ -0.000938 ┆ 0.003048  │
│ 00:00:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ UTC        ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2024-12-27 ┆ 0.006339 ┆ 0.006331 ┆ 0.006355 ┆ … ┆ -0.00127   ┆ -0.000213 ┆ 0.000086  ┆ 0.00352   │
│ 00:00:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ UTC        ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2024-12-28 ┆ 0.006339 ┆ 0.006339 ┆ 0.006339 ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 00:00:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ UTC        ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2024-12-29 ┆ 0.006342 ┆ 0.006333 ┆ 0.006343 ┆ … ┆ 0.001561   ┆ 0.002721  ┆ 0.000643  ┆ 0.000485  │
│ 00:00:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ UTC        ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2024-12-30 ┆ 0.006333 ┆ 0.006326 ┆ 0.006383 ┆ … ┆ -0.001558  ┆ -0.000798 ┆ -0.002675 ┆ -0.002751 │
│ 00:00:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ UTC        ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ 2024-12-31 ┆ 0.006369 ┆ 0.006347 ┆ 0.006409 ┆ … ┆ -0.004425  ┆ -0.007206 ┆ -0.004634 ┆ -0.002495 │
│ 00:00:00   ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
│ UTC        ┆          ┆          ┆          ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘